[package]
name = "lb-rodeo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
reqwest = "0.11.14"
tokio = { version = "1.26.0", features = ["full"] }
warp = "0.3.3"

